DNA = 'ATCGGGAATATATTGCGTTTCCGAACCCGCGGCGCGCGATATAGAGGCCGGCTAAATATCGCGCGATATTATATCGCGGCGGCGGGGGGGGGGGGGATATTAAAAAAAAACGGGGGGGGGGGGTAAAAAAAACGGGCGCCCGCTCGACTAGCTAGCGATCTGTACGATCGATCGAGA'
g_count = DNA.count('G')
c_count = DNA.count('C')
gc_count = g_count + c_count
print(gc_count/len(DNA) * 100)